#!/bin/bash

TEST_DIRECTORY=tests
VALIDATION_TEST=validate

for jy_test in $(find ${TEST_DIRECTORY} -name "${VALIDATION_TEST}"); do
    jy_test_dir=$(dirname ${jy_test})
    echo -ne "cleaning ${jy_test_dir}\n" 
    current_dir=$(pwd)
    cd "$jy_test_dir" || echo "cannot cd to $jy_test_dir" || exit 2
    rm -rf target
    cd ${current_dir}
done
