#!/bin/bash

function run_this {
    # every script actually run a set of tests
    # exit code is O only if they exit all with 0
    # output is already suppressed by the invoked script

    if [ -f ".skipTest" ]; then
	echo -e "\e[1;32mSKIPPED\e[0m\n"
	return 0
    fi

    dir=`basename "$2"`
    "$1"
    if [ $? = 0 ]
    then
	echo -e "\e[1;32m$dir OK\e[0m\n"
    else
	echo -e "\e[1;31m$dir FAILED\e[0m\n"
    fi
}

TESTDIR=tests
echo "-----------------------------------------------------"
echo "Running tests in $TESTDIR: false positives possible"
echo "Run from their respective directory to see full trace"
echo "-----------------------------------------------------"
cd $TESTDIR
for dir in `ls -d ./*/`; do
    echo `basename $dir`
    cd $dir
    for script in `ls *.sh`; do
	run_this $script $dir
    done
    cd ..
done
cd ..
