#!/bin/bash

TEST_DIRECTORY=tests
VALIDATION_TEST=validate
declare -A results

print_results () {
    FMT="%-32s%-16s\n"
    printf "$FMT" "tests" "result"
    echo "------------------------------------------------"
    for key in "${!results[@]}"; do
        printf "$FMT" "$key" "${results[$key]}"
    done
}

function run_all_tests () {

    for jy_test in $(find ${TEST_DIRECTORY} -name "${VALIDATION_TEST}"); do
        jy_test_dir=$(dirname ${jy_test})
	current_dir=$(pwd)
        cd "$jy_test_dir" || echo "cannot cd to $jy_test_dir" || exit 2
	echo "running $jy_test .."

	# execute
	./${VALIDATION_TEST}
        if [ $? = 0 ]; then
	    results[$jy_test_dir]="OK"
            echo -e "\e[1;32m$jy_test_dir OK\e[0m\n"
        else
	    results[$jy_test_dir]="FAILED"
            echo -e "\e[1;31m$jy_test_dir FAILED\e[0m\n"
        fi

        cd ${current_dir}
    done
}

run_all_tests
print_results
