#!/bin/bash
# gianmarco.bruno@ericsson.com, carlo.perocchio@ericsson.com

PREREQUISITES="pyang"

print_usage() {
    echo "usage: validate -j <JSON_FILE> -w <WHAT> [options]"
    echo ""
    echo "JSON_FILE is a document annotated with references and models like:"
    echo '"// __REFERENCE_DRAFTS__": {'
    echo '    "ietf-routing-types@2017-12-04": "rfc8294",'
    echo '    "ietf-te-types@2019-07-05": "draft-ietf-teas-yang-te-types-10",'
    echo '    "ietf-eth-tran-types@2019-03-27": "draft-ietf-ccamp-client-signal-yang-00",'
    echo '    "ietf-eth-tran-service@2019-03-27": "draft-ietf-ccamp-client-signal-yang-00"'
    echo ' },'
    echo "WHAT is one of: data, config"
    echo ""
    echo "options:"
    echo "-m M1 -m M2 .. are the directories where models are looked for (the rightmost wins)"
    echo "-f fetch to 'downloads' directory the cited documents and models (default false)"
    echo "-k keep target directory (default false)"
    echo "-s STRATEGY is one of pyang or yanglint (default)"
    echo "-v verbose"
    echo ""
    echo "this is jy  $JY_VERSION"
    echo "uses pyang  $PYANG_VERSION"
    echo "and libyang $LIBYANG_VERSION"
    echo ""
    echo "exiting: did nothing"
    exit 2
}

# global vars and their defaults
JSON_FILE=""
WHAT=""
TARGET_DIR=target
MODELS_DIR=""
DOWNLOAD_DIR=downloads
FETCH=false
KEEP=false
STRATEGY=yanglint
VERBOSE=false

THIS_SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# to suppress pushd/popd messages
pushd () {
    command pushd "$@" > /dev/null
}

popd () {
    command popd "$@" > /dev/null
}

function exit_if_failed {
    if [ $? -ne 0 ]
    then
        cleanup
        echo "failed during $1"
        exit 1
    fi
}

# usage: fetch_yang_models $JSON_FILE $DOWNLOAD_DIR
function fetch_yang_models {
    if [ "$FETCH" = true ]; then
        [ $VERBOSE = true ] && echo "..will download models from the network"
        python3 $THIS_SCRIPT_DIR/scripts/fetchModels.py -i $1 -o $2
    else
        [ $VERBOSE = true ] && echo "..will use local models for validation"
    fi
}

# pseudo-comments has been provisionally defined in the IETF TEAS Transport NBI
# Design Team in JSON as fictitious key/value pairs on a single line:
# "// TEXT" :" OTHER TEXT", for example "// router-id": "NODE-S3-ID"

function cleanup {
    [ $KEEP = true ] || rm -rf $TARGET_DIR
}

process_args() {
     while (( "$#" )); do
         case "$1" in
         -h)
             print_usage
             ;;
         -j)
             JSON_FILE="$2"
             shift 2
             ;;
         -m)
             MODELS_DIR="$MODELS_DIR $2"
             shift 2
             ;;
         -w)
             WHAT="$2"
             shift 2
             ;;
         -s)
             STRATEGY="$2"
             shift 2
             ;;
         -f)
             FETCH=true
             shift
             ;;
         -k)
             KEEP=true
             shift
             ;;
         -v)
             VERBOSE=true
             shift
             ;;
         -*)
             echo "unrecognized input $1"
             print_usage
             exit 1
             ;;
         esac
     done
     [ -z "$JSON_FILE" ] && print_usage
     [ -z "$WHAT" ] && print_usage
}

function validate_yanglint () {
    JSON_FILE=$1
    WHAT=$2
    TARGET_DIR=$3

    JTOX_FILE=$TARGET_DIR/_temp.yanglint
    JSON_STRIPPED=${TARGET_DIR}/${JSON_FILE%.json}-stripped.json
    cp $JSON_FILE $JSON_STRIPPED

    echo "searchpath ${TARGET_DIR}" >> $JTOX_FILE
    for i in $ALL_YANG_FILES; do
        echo "add -i $i" >> $JTOX_FILE
    done
    echo "data -t $WHAT $JSON_STRIPPED" >> $JTOX_FILE
    echo "exit" >> $JTOX_FILE

    [ $VERBOSE = true ] && echo "<<<" && cat $JTOX_FILE && echo ">>>"

    # strip comments
    python $THIS_SCRIPT_DIR/scripts/Stripper.py -i $JSON_STRIPPED --indent 2 --clean
    exit_if_failed "stripping comments"

    # the contract with yanglint is that validation is OK iff
    # nothing is written on STDERR so we capture and check it
    # and our testsuite currently expects the magic string
    # "No errors found." to be happy
    ANSWER=$(cat $JTOX_FILE | yanglint 2>&1)

    EXIT_CODE=0
    if [ "z$ANSWER" == "z" ]; then
        >&2 echo "No errors found."
    else
        echo $ANSWER
        EXIT_CODE=1
    fi
    return $EXIT_CODE
}

function validate_pyang() {
    JSON_FILE=$1
    WHAT=$2
    TARGET_DIR=$3

    JTOX_FILE=$TARGET_DIR/_temporary.jtox
    pyang -p $TARGET_DIR -f jtox -o $JTOX_FILE $ALL_YANG_FILES
    exit_if_failed "writing jtox"

    echo "preparing step (2) stripping pseudo-comments from JSON .."
    # we want to keep the original JSON unchanged
    JSON_TMP=${TARGET_DIR}/$(basename $JSON_FILE)
    python $THIS_SCRIPT_DIR/scripts/Stripper.py -i=${JSON_FILE} -o=${JSON_TMP} --clean
    exit_if_failed "stripping comments"

    echo "(2) converting JSON to XML .."
    XML_BASE=$(basename ${JSON_FILE%.json})
    XML_TMP=${XML_BASE}_tmp.xml
    XML_FILE=${XML_BASE}.xml
    json2xml -t $WHAT -o $TARGET_DIR/$XML_TMP $JTOX_FILE $JSON_TMP
    exit_if_failed "converting JSON to XML"

    # optionally beautify XML if xmllint is installed
    if [ command -v xmllint >/dev/null 2>&1 ]; then
        echo "I require xmllint but it's not installed.  Skipping."
        cp $TARGET_DIR/$XML_TMP $TARGET_DIR/$XML_FILE
    else
        echo "Beautifying XML"
        xmllint --format $TARGET_DIR/$XML_TMP > $TARGET_DIR/$XML_FILE
        exit_if_failed "beautifying XML"
    fi
    rm $TARGET_DIR/$XML_TMP

    echo "(3) writing schemas .."
    # It seems that yang2dsdl wants the yang modules in the dir it was called from
    # So we move temporarily there and then resume from the current directory.

    pushd .
    cd $TARGET_DIR
    pwd
    yang2dsdl -t $WHAT -d . -b _placeholder *.yang
    popd
    exit_if_failed "writing schemas"

    echo "(4) validating XML .."
    # For same purpose we move temporarily to the directory where the schemas are placed.

    pushd .
    cd $TARGET_DIR
    yang2dsdl -s -b _placeholder -t $WHAT -v $XML_FILE
    popd
}

function check_prerequisites() {
    for PROGRAM in $@; do
	[ -z "$(command -v $PROGRAM)" ] &&
	   echo "missing $PROGRAM - try 'sudo apt install $PROGRAM'" && exit 1
    done
}

main() {
    check_prerequisites "$PREREQUISITES"
    process_args $@

    if [ $VERBOSE = true ]; then
    echo "----------------"
    echo "JSON FILE      $JSON_FILE"
    echo "WHAT           $WHAT"
    echo "-- behaviours --"
    echo "KEEP TARGET    $KEEP"
    echo "FETCH          $FETCH"
    echo "STRATEGY       $STRATEGY"
    echo "-- places --"
    echo "DOWNLOAD DIR   $DOWNLOAD_DIR"
    echo "MODELS DIR     $MODELS_DIR"
    echo "TARGET DIR     $TARGET_DIR"
    echo "----------------"
    fi

    if [ -d "$TARGET_DIR" ]; then
        echo "target directory exists .. exiting"
	cleanup
        exit 2
    fi
    mkdir $TARGET_DIR

    # fetch to $DOWNLOAD_DIR
    if [ $FETCH == "true" ]; then
        rm -rf $DOWNLOAD_DIR && mkdir -p $DOWNLOAD_DIR
        [ $VERBOSE == "true" ] && echo "download references and models to $DOWNLOAD_DIR"
        fetch_yang_models $JSON_FILE $DOWNLOAD_DIR
    fi

    # copy yang files from all model directories
    for THIS_MODELS_DIR in $MODELS_DIR; do
        [ $VERBOSE == "true" ] && echo "using models in $THIS_MODELS_DIR"
        MODELS=`ls $THIS_MODELS_DIR/*.yang 2> /dev/null`
        [ -z "$MODELS" ] && echo "warning: no models in $THIS_MODELS_DIR"
        cp $THIS_MODELS_DIR/*.yang -t $TARGET_DIR 2> /dev/null
    done

    ALL_YANG_FILES="`ls ${TARGET_DIR}/*.yang 2> /dev/null`"
    [ -z "$ALL_YANG_FILES" ] && echo "no yang files in $TARGET_DIR to be evaluated" && cleanup && exit 2
    sed "s/ /\n/g" <<< $ALL_YANG_FILES > /dev/null

    echo "make validation using $STRATEGY"

    if [ $STRATEGY == "pyang" ]; then
        validate_pyang $JSON_FILE $WHAT $TARGET_DIR
    elif [ $STRATEGY == "yanglint" ]; then
        validate_yanglint $JSON_FILE $WHAT $TARGET_DIR
    else
        echo "unknown strategy $STRATEGY"
        exit 2
    fi

    exit_if_failed "validation"

    # do not write anything on stdout otherwise
    # the test driver gets confused
    cleanup
    return 0
}


main "$@"
